source 'https://rubygems.org'

gem 'cool.io', '~>1.5.4'
gem 'oj', '~>3.10.0'
gem 'json', '~>2.3.0'

gem 'fluentd', '~>1.13.1'

gem 'fluent-plugin-elasticsearch', '~>3.8.0'
gem 'fluent-plugin-prometheus', '~>1.7.0'
gem 'fluent-plugin-splunk-enterprise', '~>0.10.0'
gem 'fluent-plugin-kafka', '~>0.12.1'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.7.2'
gem 'fluent-plugin-remote_syslog_tls', '~>1.0.2'

# filter plugins
gem 'fluent-plugin-concat', '~>2.4.0'
gem 'fluent-plugin-rewrite-tag-filter', '~>2.2.0'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'

gem 'zookeeper', '~>1.4.11'
