source 'https://rubygems.org'

gem 'cool.io'
gem 'oj'
gem 'json'

gem 'fluentd'

# Input / Output plugins:
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-splunk-enterprise'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-kubernetes_metadata_filter'
gem 'fluent-plugin-remote_syslog_tls'
gem 'fluent-plugin-gelf-hs'

# filter plugins
gem 'fluent-plugin-concat'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-multi-format-parser'

# third party
gem 'zookeeper'
